feat(config): make sample rate configurable in SentryClient
flownative/flow-sentry pull request #25
Opened 2024-07-02 07:40 UTC by das-nagnag

In our project we just started using Sentry but since we expect fairly high numbers of issues, we'd like to be able to adjust the sampleRate as sampling *all* issues could prove quite costly (literally) to us. From what I can tell these two changed files should already do the job but if there's anything I missed please let me know and I'll be happy to make the suggested changes, too!

2024-08-01 14:04 UTC, das-nagnag commented
Hi @kdambekalns and @robertlemke, huge sorry for the direct ping! Do you see a possibility for this PR to be merged (and ideally a new tag/release to be made) or is that unlikely/not a priority atm? Apologies again and thank you in advance!

2024-08-02 07:53 UTC, kdambekalns approved these changes
From looking at it, that seems reasonable.

Sentry docs: https://docs.sentry.io/platforms/php/configuration/sampling/

2024-08-02 07:55 UTC, kdambekalns requested changes
Wait, unless explicitly set, this will now sample with a rate of 0.0

2024-08-02 08:02 UTC, kdambekalns commented
Some more details: when the env var is not set, `getenv()` will return false (and the `%env:…%` processing is based on that), so the `??` will not trigger. This
```php
$setting = getenv('SENTRY_SAMPLE_RATE'); // not set!
$sampleRate = $setting ?? 1; // $setting is false
var_dump((float)$sampleRate); // false is cast to 0
```
results in `float(0)`.

I'd suggest to simply put `1` into the default settings, if someone wants to adjust it, it can done by setting it directly or to an environment variable as needed.

2024-08-02 08:02 UTC, kdambekalns commented on Configuration/Settings.yaml
> +    sampleRate: "%env:SENTRY_SAMPLE_RATE%"
```suggestion
    sampleRate: 1
```

2024-08-02 14:50 UTC, das-nagnag commented
Thank you so much for your feedback! I wasn't aware of that shortcoming of my changes, thank you for noting that and giving the detailed demonstration, I appreciate it! I'll have a bit of a think over the weekend if I can figure out a nice and clean way around that, otherwise your suggested changes obviously also would work.

2024-09-02 06:17 UTC, das-nagnag commented
Hi @kdambekalns, I am extremely sorry for my late reply. I've been struck down for two weeks with a nasty covid infection and right after that I had two weeks of vacation booked off work, so I was "out of office" for nearly a month. Even then, with all that time, I didn't come up with a better/simpler solution than the one you proposed so I'm happy to move forward with your suggestion :)

2024-09-18 08:31 UTC, kdambekalns approved these changes

2024-09-18 08:31 UTC, merged

2024-09-24 09:28 UTC, das-nagnag commented
thank you! ❤️